<?php

namespace {

    use SilverStripe\Assets\Image;
    use SilverStripe\Forms\FieldList;
    use SilverStripe\ORM\DataExtension;

    class MemberExtension extends DataExtension
    {
        private static $db = [
            'Position' => 'Text',
            'Bio'      => 'HTMLText'
        ];

        private static $has_one = [
            'ProfileImage' => Image::class
        ];

        private static $has_many = [
            'Socials'=> Socials::class,
        ];

        private static $owns = [
            'ProfileImage'
        ];

        public function updateCMSFields(FieldList $fields)
        {
            parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
        }
    }
}
