<?php

namespace {

    use SilverStripe\Core\ClassInfo;
    use SilverStripe\ORM\DataObject;

    class Section extends DataObject
    {
        private static $default_sort = 'Sort';
        private static $singular_name = 'Content Section';

        private static $db = [
            'Name'    => 'Text',
            'Type'    => 'Varchar',
            'Archive' => 'Boolean',
            'Sort'    => 'Int'
        ];

        private static $has_one = [
            'Page' => Page::class,
        ];

        private static $owns = [

        ];

        private static $summary_fields = [
            'Name',
            'Status'
        ];

        private function getSectionTypes()
        {
            $sectionTypes = array();
            $classes = ClassInfo::getValidSubClasses('Section');
            foreach ($classes as $type) {
                $instance = self::singleton($type);
                $sectionTypes[$instance->ClassName] = $instance->singular_name();
            }
            return $sectionTypes;
        }

        public function getCMSFields()
        {
            return parent::getCMSFields(); // TODO: Change the autogenerated stub
        }
    }
}
